# 服务端口
server:
  port: 8087
  servlet:
    context-path: /elm-mybatisplus




spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_springboot_elm?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Wei20021016
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis
mybatis-plus:
  type-aliases-package: com.elm.domin.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

logging:
  level:
    com:
      baomidou:
        mybatisplus: debug
# 默认根据日志配置文件名字查找，不需要指定

#springdoc相关配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.elm.controller # 扫描的包，注意改成自己的包
#    - group: "管理端"
#      paths-to-match: '/admin/**'
#      packages-to-scan: com.my.controller
#    - group: "用户端"
#      paths-to-match: '/user/**'
#      packages-to-scan: com.my.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn